### PR TITLE
fix issues #2 masafxsln Project incloud

### LINKED ISSUE #2: dotnet new new masafx and restore failed
Description
通过cli创建masafx后，提示restore失败

Environment
.Net SDK Version:
MASA Framework Version: Masa.Template::0.6.862

Demo
image

### PR DESCRIPTION
**Pull request by JaneConan**
fix #2

### CODE REVIEW

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
Thank you very much for your reply, but it is not the cause of the error, it is correct here, we have fixed it in https://github.com/masastack/MASA.Templates/pull/5

**Comment by zhenlei520** [comment]
The current name of the template project is easy to confuse people. We will rename the template project in the future to ensure that it is easier to understand. If you are interested, you can participate together

**Comment by zhenlei520** [comment]
image

**Pull request closed without merging**
